/**
 * Kagi → Claude remote MCP connector (Cloudflare Worker).
 *
 *   Claude (web/mobile)  --OAuth 2.1-->  this Worker  --Bot key-->  Kagi v1 API
 *
 * - OAuthProvider (workers-oauth-provider) fronts everything, implementing the
 *   /token and /register (DCR) endpoints and protecting the MCP routes.
 * - The /authorize consent screen (single shared password) lives in auth.ts.
 * - KagiMCP is the MCP server itself, exposing two tools that proxy to Kagi.
 *   The Kagi API key is a Worker secret — it never leaves the server, so even
 *   though Anthropic's cloud connects to us, the key is never exposed to Claude.
 */

import OAuthProvider from "@cloudflare/workers-oauth-provider";
import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import authApp from "./auth";
import { kagiSearch, kagiExtract } from "./kagi";

// Cloudflare.Env is generated by `wrangler types` from wrangler.jsonc (bindings
// + vars: OAUTH_KV, MCP_OBJECT, KAGI_AUTH_SCHEME, KAGI_API_BASE). Secrets set via
// `wrangler secret put` aren't in there, so we add them.
export interface Env extends Cloudflare.Env {
  KAGI_API_KEY: string;
  LOGIN_PASSWORD: string;
}

type Props = { userId: string };

export class KagiMCP extends McpAgent<Env, unknown, Props> {
  server = new McpServer({ name: "Kagi", version: "1.0.0" });

  async init() {
    // Tool handlers may throw — the SDK converts thrown errors into a
    // CallToolResult with isError:true, so no per-tool try/catch is needed.
    this.server.registerTool(
      "kagi_search",
      {
        title: "Kagi search",
        description:
          "Fetch web results for a query using the Kagi Search API. Use for general search and when the user explicitly tells you to 'fetch' results/information. Returns markdown.",
        inputSchema: {
          query: z
            .string()
            .describe("A concise, keyword-focused search query. Include essential context for standalone use."),
          workflow: z
            .enum(["search", "news", "videos", "podcasts", "images"])
            .default("search")
            .describe(
              "Result type. 'news' for current events, 'videos' for video content, 'podcasts' for audio, 'images' for images, or default 'search' for a general SERP.",
            ),
          limit: z.number().int().min(1).max(1024).default(10).describe("Maximum results per category."),
          extract_count: z
            .number()
            .int()
            .min(0)
            .max(10)
            .default(0)
            .describe("Number of top results to also fetch full page content for, inline as markdown."),
          include_domains: z
            .array(z.string())
            .optional()
            .describe("Restrict results to these domains, e.g. ['docs.python.org']."),
          exclude_domains: z
            .array(z.string())
            .optional()
            .describe("Exclude results from these domains, e.g. ['pinterest.com']."),
          time_relative: z
            .enum(["day", "week", "month"])
            .optional()
            .describe("Restrict to results from the last day/week/month. Mutually exclusive with after/before."),
          after: z.string().optional().describe("Only results on/after this ISO date, e.g. '2024-01-15'."),
          before: z.string().optional().describe("Only results on/before this ISO date, e.g. '2024-12-31'."),
          file_type: z.string().optional().describe("Restrict to a file type, e.g. 'pdf' (no leading dot)."),
          lens_id: z
            .string()
            .optional()
            .describe(
              "Apply a Kagi lens. Built-ins: '2' Academic, '1' Forums, '15' Programming, '29' News 360, '120' Recipes, '107' Small Web. Mutually exclusive with the domain/time/file filters.",
            ),
        },
      },
      async (args) => {
        const text = await kagiSearch(this.env, {
          query: args.query,
          workflow: args.workflow,
          limit: args.limit,
          extractCount: args.extract_count,
          includeDomains: args.include_domains,
          excludeDomains: args.exclude_domains,
          timeRelative: args.time_relative,
          after: args.after,
          before: args.before,
          fileType: args.file_type,
          lensId: args.lens_id,
        });
        return { content: [{ type: "text", text }] };
      },
    );

    this.server.registerTool(
      "kagi_extract",
      {
        title: "Kagi extract",
        description:
          "Extract the full content of a web page as markdown using the Kagi Extract API. Use to read a page's content when needed.",
        inputSchema: {
          url: z
            .url()
            .describe("The HTTPS URL of the page to extract content from.")
            .refine((u) => u.startsWith("https://"), "URL must use https://"),
        },
      },
      async ({ url }) => {
        const text = await kagiExtract(this.env, url);
        return { content: [{ type: "text", text }] };
      },
    );
  }
}

// `agents`, workers-oauth-provider and the generated runtime types each bundle a
// slightly different @cloudflare/workers-types (the getSetCookie-on-Headers diff),
// so these structurally-identical handlers don't line up by name. The casts are
// type-only — every handler is runtime-correct.
/* eslint-disable @typescript-eslint/no-explicit-any */
export default new OAuthProvider({
  // Expose both transports. Modern Claude uses streamable HTTP (/mcp); /sse is
  // kept for older clients. Add whichever URL Claude accepts as the connector.
  apiHandlers: {
    "/sse": KagiMCP.serveSSE("/sse", { binding: "MCP_OBJECT" }) as any,
    "/mcp": KagiMCP.serve("/mcp", { binding: "MCP_OBJECT" }) as any,
  },
  defaultHandler: authApp as any,
  authorizeEndpoint: "/authorize",
  tokenEndpoint: "/token",
  clientRegistrationEndpoint: "/register",
});
